Bump to 3.0.5
Manta-Network/Manta pull request #202
Opened 2021-09-27 09:44 UTC by ghzlatarev

2021-09-27 11:09 UTC, ghzlatarev commented
@stechu this is a draft-release that has been tagged with `v3.0.5-calamari.kusama`

2021-09-28 06:06 UTC, grenade approved these changes

2021-09-28 06:06 UTC, stechu requested changes

2021-09-28 06:06 UTC, stechu commented on CHANGELOG.md
> +## v0.5.0
Why v0.5.0?

2021-09-28 07:50 UTC, Dengjianping commented
Do we need a section that shows about `spec_version` change?

2021-09-29 01:23 UTC, Dengjianping approved these changes
LGTM!

2021-09-29 02:22 UTC, stechu approved these changes
LGTM.

2021-09-29 02:22 UTC, merged