[Manta] [Ready to merge] Integrate manta pay pallet
Manta-Network/Manta pull request #21
Opened 2021-05-03 17:14 UTC by zhenfeizhang

The current integration has been tested for both initialization and minting function.
The transfer and reclaim functions are to be tested -- requires some updates on the CLI.

2021-05-03 22:31 UTC, stechu requested changes
LGTM in general, two things left:
1. Update the `runtime/Cargo.toml` to `calamari` branch
2. should merge master after #18 is merged though.

2021-05-03 22:31 UTC, stechu commented on runtimes/manta/runtime/Cargo.toml
> +# todo: update the branch dependency to calamari once this branch is merged
This branch has been merged now :)

2021-05-03 23:56 UTC, zhenfeizhang commented on runtimes/manta/runtime/Cargo.toml
> +# todo: update the branch dependency to calamari once this branch is merged
done

2021-05-04 00:04 UTC, zhenfeizhang commented
> LGTM in general, two things left:
> 
>     1. Update the `runtime/Cargo.toml` to `calamari` branch
> 
>     2. should merge master after #18 is merged though.

Done.

2021-05-04 00:43 UTC, stechu commented
Thanks for the changes.

2021-05-04 00:43 UTC, merged