[Calamari]Bump deps to polkadot-v0.9.11
Manta-Network/Manta pull request #211
Opened 2021-10-11 11:26 UTC by Dengjianping

## Description

closes: #210 

## Deps Changes
Polkadot Changes:
1. https://github.com/paritytech/polkadot/pull/3906
2. https://github.com/paritytech/polkadot/pull/3911
3. https://github.com/paritytech/polkadot/pull/3818
4. https://github.com/paritytech/polkadot/pull/3916
5. https://github.com/paritytech/polkadot/pull/3898
6. https://github.com/paritytech/polkadot/pull/3627
7. https://github.com/paritytech/polkadot/pull/3901
8. https://github.com/paritytech/polkadot/pull/3629

Substrate Changes:
1. https://github.com/paritytech/substrate/pull/9844
2. https://github.com/paritytech/substrate/pull/9552
3. https://github.com/paritytech/substrate/pull/9834

Cumulus Changes:
1. https://github.com/paritytech/cumulus/pull/623

statemine diffs between:

fa116cfbfb470a8114fc02f9d2e3c0a5ab6c7193 -> 0.9.10
ede4d527c4fc5d84c43216b408a873625488574b-> 0.9.11

## Our Changes

### Client

1. version from `3.0.5` to `3.0.6`.
2. Removed `fn rpc_http_threads` and `telemetry_external_transport` from  `RelayChainCli`: [change](https://github.com/Manta-Network/Manta/blob/jamie/upgrade-deps-v0.9.11/node/src/command.rs#L529)
3. Removed macro `native_executor_instance`, we have to manually implement it: [change](https://github.com/Manta-Network/Manta/blob/jamie/upgrade-deps-v0.9.11/node/src/service.rs#L46)
4. Refactor rpc service: https://github.com/Manta-Network/Manta/blob/jamie/upgrade-deps-v0.9.11/node/src/rpc.rs

### Runtime

1. New associated type `OperationalFeeMultiplier` for  `pallet_transaction_payment`: [change](https://github.com/Manta-Network/Manta/blob/jamie/upgrade-deps-v0.9.11/runtime/calamari/src/lib.rs#L236)

   ```rust
   pub const OperationalFeeMultiplier: u8 = 5;
   ```

   This means A fee mulitplier for `Operational` extrinsics to compute "virtual tip" to boost their `priority`.

   See more details from here: [OperationalFeeMultiplier](https://github.com/paritytech/substrate/blob/polkadot-v0.9.11/frame/transaction-payment/src/lib.rs#L267)

   I think 5 should be fine.

2. New associated types `AssetTrap` and `AssetClaims`. This is for xcm configuration. For now, we don't enable xcm in calamari, we can just follow statemint' configuration, it should be fine.

   More details: [associated types](https://github.com/Manta-Network/Manta/blob/jamie/upgrade-deps-v0.9.11/runtime/calamari/src/lib.rs#L383)

3. Update configuration for `pallet_xcm`. Just  follow statemint' configuration.

   ```rust
   const VERSION_DISCOVERY_QUEUE_SIZE: u32 = 100;
   type Origin = Origin;
   type Call = Call;
   ```

   More details: https://github.com/Manta-Network/Manta/blob/jamie/upgrade-deps-v0.9.11/runtime/calamari/src/lib.rs#L405

4. New associated type `MaxAuthorities` for `pallet_aura`.

   ```rust
   pub const MaxAuthorities: u32 = 100_000;
   type MaxAuthorities = MaxAuthorities;
   ```

   This means The maximum number of authorities that the pallet can hold.

   Now, we don't allow comunity to run collator, we can consider it later.

   More details: https://github.com/paritytech/substrate/blob/polkadot-v0.9.11/frame/aura/src/lib.rs#L75
5. Bump `spec_version`to 2.
---

## Tests
- [x] Does key injection script work (only for calamari-testnet)
- [x] Check block production
- [x] Sudo system.setCode upgrade
- [x] Force transfer balances
- [x] Pass sudo to multi-sig account
- [x] Upgrade with authorizeUpgrade + enactAuthorized
- [x] Check average block time is ~12 seconds
- [x] Check dropping and reconnecting a collator
- [x] Native binary replacement

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (`manta` or `manta-pc`) with right title (start with [Manta] or [Manta-PC]),
- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests.
- [ ] Updated relevant documentation in the code.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [x] If runtime changes, need to update the version numbers properly:
   * `authoring_version`: The version of the authorship interface. An authoring node will not attempt to author blocks unless this is equal to its native runtime.
   * `spec_version`: The version of the runtime specification. A full node will not attempt to use its native runtime in substitute for the on-chain Wasm runtime unless all of spec_name, spec_version, and authoring_version are the same between Wasm and native.
   * `impl_version`: The version of the implementation of the specification. Nodes are free to ignore this; it serves only as an indication that the code is different; as long as the other two versions are the same then while the actual code may be different, it is nonetheless required to do the same thing. Non-consensus-breaking optimizations are about the only changes that could be made which would result in only the impl_version changing.
   * `transaction_version`: The version of the extrinsics interface. This number must be updated in the following circumstances: extrinsic parameters (number, order, or types) have been changed; extrinsics or pallets have been removed; or the pallet order in the construct_runtime! macro or extrinsic order in a pallet has been changed. If this number is updated, then the spec_version must also be updated 
- [ ] If needed, notify the committer this is a draft-release and a tag is needed after merging the PR.
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics

2021-10-13 12:17 UTC, ghzlatarev commented
Can you add the 2 statemint commits you used to get their diff.

2021-10-13 12:20 UTC, ghzlatarev requested changes
Please update the `CHANGELOG.md` file as well.

2021-10-13 12:21 UTC, ghzlatarev requested changes
Can you add the 2 statemint commits you used to get their diff.

2021-10-13 12:27 UTC, ghzlatarev commented on runtime/manta-pc/Cargo.toml
> +hex-literal = { version = '0.3.3', optional = true }
don't we need `default-features=false`

2021-10-13 14:17 UTC, ghzlatarev requested changes

2021-10-13 14:17 UTC, ghzlatarev commented on runtime/calamari/src/lib.rs
> +	const VERSION_DISCOVERY_QUEUE_SIZE: u32 = 100;
Let's move this to a parameter_types! macro like all the other constants.

2021-10-14 05:37 UTC, Dengjianping commented on runtime/calamari/src/lib.rs
> +	const VERSION_DISCOVERY_QUEUE_SIZE: u32 = 100;
It seems we cannot make this constant to as storage constant. Because it's in trait definition.
See here: https://doc.rust-lang.org/reference/items/associated-items.html#associated-constants-examples

2021-10-14 05:42 UTC, Dengjianping commented on runtime/manta-pc/Cargo.toml
> +hex-literal = { version = '0.3.3', optional = true }
It's fine, because only benchmarking needs `hex-literal`.

2021-10-14 05:45 UTC, Dengjianping commented
> Can you add the 2 statemint commits you used to get their diff.

Done.

2021-10-14 06:17 UTC, stechu approved these changes
LGTM. Should either keep or remove `try-runtime` feature entirely.

2021-10-16 05:53 UTC, Dengjianping commented
> Please update the `CHANGELOG.md` file as well.

Done.

2021-10-16 07:03 UTC, ghzlatarev commented
LGTM

2021-10-16 07:15 UTC, ghzlatarev approved these changes

2021-10-16 07:15 UTC, merged