[manta]Migrate to new method of declaring constants
Manta-Network/Manta pull request #405
Opened 2022-02-17 15:11 UTC by Dengjianping

## Description

```rust
pub const MaxLocks: u32 = 50; 

type MaxLocks = MaxLocks;
```
=> 
```rust
type MaxLocks = ConstU32<50>;
```

But I don't change some constants like:
```rust
pub const Offset: u32 = 0; 
```
If I change it, it's not that readable.

closes: #389

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (`manta` or `dolphin`) with right title (start with [Manta] or [Dolphin]),
- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests.
- [ ] Updated relevant documentation in the code.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] If runtime changes, need to update the version numbers properly:
   * `authoring_version`: The version of the authorship interface. An authoring node will not attempt to author blocks unless this is equal to its native runtime.
   * `spec_version`: The version of the runtime specification. A full node will not attempt to use its native runtime in substitute for the on-chain Wasm runtime unless all of spec_name, spec_version, and authoring_version are the same between Wasm and native.
   * `impl_version`: The version of the implementation of the specification. Nodes are free to ignore this; it serves only as an indication that the code is different; as long as the other two versions are the same then while the actual code may be different, it is nonetheless required to do the same thing. Non-consensus-breaking optimizations are about the only changes that could be made which would result in only the impl_version changing.
   * `transaction_version`: The version of the extrinsics interface. This number must be updated in the following circumstances: extrinsic parameters (number, order, or types) have been changed; extrinsics or pallets have been removed; or the pallet order in the construct_runtime! macro or extrinsic order in a pallet has been changed. If this number is updated, then the spec_version must also be updated 
- [ ] If needed, notify the committer this is a draft-release and a tag is needed after merging the PR.
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics
- [ ] If needed, bump `version` for every crate.
- [ ] If import a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- [ ] If needed, update our Javascript/Typescript APIs. These APIs are offcially used by exchanges or community developers.
- [ ] If we're going to issue a new release, freeze the code one week early(it depends, but usually it's one week), ensure we have enough time for related testing.
- [ ] Check if inheriting any upstream runtime storage migrations. If any, perform tests with `try-runtime`.

2022-02-17 15:16 UTC, ghzlatarev approved these changes

2022-02-17 19:11 UTC, ghzlatarev commented
@Dengjianping merge conflicts

2022-02-23 20:02 UTC, stechu requested changes

2022-02-23 20:02 UTC, stechu commented on runtime/manta/src/lib.rs
> +	type MaxScheduledPerBlock = ConstU32<50>;
Can you move the comment here?

2022-02-23 20:02 UTC, stechu commented on runtime/manta/src/lib.rs
> +	type MinCandidates = ConstU32<3>;
same here.

2022-02-23 20:02 UTC, stechu commented
LGTM. Pending minor changes.

2022-02-24 02:57 UTC, stechu requested changes

2022-02-24 02:57 UTC, stechu commented on runtime/calamari/src/lib.rs
> +									 // should be a multiple of session or things will get inconsistent
Can you fix the white space here?

2022-02-24 04:36 UTC, Dengjianping commented on runtime/calamari/src/lib.rs
> +									 // should be a multiple of session or things will get inconsistent
It's formatted by fmt.

2022-02-25 02:17 UTC, stechu approved these changes

2022-02-25 02:18 UTC, merged