Add a corner case for collator-selection
Manta-Network/Manta pull request #411
Opened 2022-02-23 15:05 UTC by Dengjianping

## Description

closes: #360 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (`manta` or `dolphin`) with right title (start with [Manta] or [Dolphin]),
- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests.
- [ ] Updated relevant documentation in the code.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] If runtime changes, need to update the version numbers properly:
   * `authoring_version`: The version of the authorship interface. An authoring node will not attempt to author blocks unless this is equal to its native runtime.
   * `spec_version`: The version of the runtime specification. A full node will not attempt to use its native runtime in substitute for the on-chain Wasm runtime unless all of spec_name, spec_version, and authoring_version are the same between Wasm and native.
   * `impl_version`: The version of the implementation of the specification. Nodes are free to ignore this; it serves only as an indication that the code is different; as long as the other two versions are the same then while the actual code may be different, it is nonetheless required to do the same thing. Non-consensus-breaking optimizations are about the only changes that could be made which would result in only the impl_version changing.
   * `transaction_version`: The version of the extrinsics interface. This number must be updated in the following circumstances: extrinsic parameters (number, order, or types) have been changed; extrinsics or pallets have been removed; or the pallet order in the construct_runtime! macro or extrinsic order in a pallet has been changed. If this number is updated, then the spec_version must also be updated 
- [ ] If needed, notify the committer this is a draft-release and a tag is needed after merging the PR.
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics
- [ ] If needed, bump `version` for every crate.
- [ ] If import a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- [ ] If needed, update our Javascript/Typescript APIs. These APIs are offcially used by exchanges or community developers.
- [ ] If we're going to issue a new release, freeze the code one week early(it depends, but usually it's one week), ensure we have enough time for related testing.
- [ ] Check if inheriting any upstream runtime storage migrations. If any, perform tests with `try-runtime`.

2022-02-24 03:41 UTC, Garandor approved these changes
LGTM

2022-02-25 00:56 UTC, stechu requested changes

2022-02-25 00:56 UTC, stechu commented on pallets/collator-selection/src/tests.rs
> +	// 1. Set orignal bond as 100KMA.
`10` from the code?

2022-02-25 00:56 UTC, stechu commented on pallets/collator-selection/src/tests.rs
> +	// 3. increase bond to 150KMA.
`15` from the code?

2022-02-25 00:56 UTC, stechu commented on pallets/collator-selection/src/tests.rs
> +	// 4. The owner should get 100KMA back instead of 150KMA.
See previous comments.

2022-02-28 09:41 UTC, ghzlatarev commented on pallets/collator-selection/src/tests.rs
> +		assert_eq!(0, Balances::reserved_balance(candidate_2));
It might be better to reserve some more of the balance in another way in order not check against 0.

2022-02-28 09:41 UTC, ghzlatarev commented on pallets/collator-selection/src/tests.rs
> +		assert_eq!(100, Balances::free_balance(candidate_1));
Can you write a comment that they start off with 100 in this mock runtime.

2022-03-01 11:25 UTC, ghzlatarev approved these changes

2022-03-01 22:03 UTC, stechu approved these changes

2022-03-01 22:03 UTC, merged