Instructions to sign DCO
Manta-Network/Manta pull request #439
Opened 2022-03-09 13:35 UTC by ghzlatarev

## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (`manta` or `dolphin`) with right title (start with [Manta] or [Dolphin]),
- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests.
- [ ] Updated relevant documentation in the code.
- [ ] Added **one** line describing your change in `<branch>/CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] If runtime changes, need to update the version numbers properly:
   * `authoring_version`: The version of the authorship interface. An authoring node will not attempt to author blocks unless this is equal to its native runtime.
   * `spec_version`: The version of the runtime specification. A full node will not attempt to use its native runtime in substitute for the on-chain Wasm runtime unless all of spec_name, spec_version, and authoring_version are the same between Wasm and native.
   * `impl_version`: The version of the implementation of the specification. Nodes are free to ignore this; it serves only as an indication that the code is different; as long as the other two versions are the same then while the actual code may be different, it is nonetheless required to do the same thing. Non-consensus-breaking optimizations are about the only changes that could be made which would result in only the impl_version changing.
   * `transaction_version`: The version of the extrinsics interface. This number must be updated in the following circumstances: extrinsic parameters (number, order, or types) have been changed; extrinsics or pallets have been removed; or the pallet order in the construct_runtime! macro or extrinsic order in a pallet has been changed. If this number is updated, then the spec_version must also be updated 
- [ ] If needed, notify the committer this is a draft-release and a tag is needed after merging the PR.
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics
- [ ] If needed, bump `version` for every crate.
- [ ] If import a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- [ ] If needed, update our Javascript/Typescript APIs. These APIs are offcially used by exchanges or community developers.
- [ ] If we're going to issue a new release, freeze the code one week early(it depends, but usually it's one week), ensure we have enough time for related testing.
- [ ] Check if inheriting any upstream runtime storage migrations. If any, perform tests with `try-runtime`.

2022-03-11 20:07 UTC, stechu commented
Can you put this in a contribution guideline markdown?
something like:
https://github.com/atom/atom/blob/master/CONTRIBUTING.md

2022-03-14 09:04 UTC, ghzlatarev commented
> Can you put this in a contribution guideline markdown? something like: https://github.com/atom/atom/blob/master/CONTRIBUTING.md

Will do.

2022-03-18 01:44 UTC, Dengjianping approved these changes
LGTM!

2022-03-18 18:45 UTC, Garandor requested changes
Pretty clear instructions, just found a few typos to fix

2022-03-18 18:45 UTC, Garandor commented on CONTRIBUTING.md
> +* **Describe the exact network configuraiton** include parachain node version, relay chain node version and any tooling you may be using, such as polkadot-launch and its configurations.
typo configuraiton

2022-03-18 18:45 UTC, Garandor commented on CONTRIBUTING.md
> +* **Wich version of Manta/Calamari are you using?**
typo, Wich

2022-03-18 18:45 UTC, Garandor commented on CONTRIBUTING.md
> +* **Are you working with the Manta/Calamari mainnets or have you depoloyed locally**
depoloyed

2022-03-18 18:45 UTC, Garandor commented on CONTRIBUTING.md
> +Enhancement suggestions are tracked as [GitHub issues](https://guides.github.com/features/issues/).Create an issue on that repository and provide the following information:
space after dot

2022-03-18 18:45 UTC, Garandor commented on CONTRIBUTING.md
> +4. If you have a significant design decision to make please document it as an ehancement request first, so we can review it and provide feedback before any code is written.
ehancement

2022-03-18 18:45 UTC, Garandor commented on CONTRIBUTING.md
> +While the prerequisites above must be satisfied prior to having your pull request reviewed, the reviewer(s) may ask you to complete additional design work, tests, or other changes before your pull re
isnt "must be satisfied" a bit too strong for a "guideline"?

2022-03-18 18:45 UTC, Garandor commented on CONTRIBUTING.md
> +* Write comments on top of your code.
we don't do inline comments to the right of a code line? Good to know :D

2022-03-23 09:47 UTC, grenade approved these changes

2022-03-23 14:46 UTC, Garandor commented on CONTRIBUTING.md
> +* **Perform a cursory search in the Manta Network organization to see if the problem has already been reported. If it has **and the issue is still open**, add a comment to the existing issue instead
this has one too many sets of **

2022-03-23 14:48 UTC, Garandor approved these changes

2022-03-23 16:10 UTC, merged