Fix assetmanager metadata update
Manta-Network/Manta pull request #461
Opened 2022-03-25 18:57 UTC by ghzlatarev

Signed-off-by: ghzlatarev <ghzlatarev@gmail.com>

## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests.
- [ ] Updated relevant documentation in the code.
- [ ] Added **one** line describing your change in `<branch>/CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] If runtime changes, need to update the version numbers properly:
   * `authoring_version`: The version of the authorship interface. An authoring node will not attempt to author blocks unless this is equal to its native runtime.
   * `spec_version`: The version of the runtime specification. A full node will not attempt to use its native runtime in substitute for the on-chain Wasm runtime unless all of spec_name, spec_version, and authoring_version are the same between Wasm and native.
   * `impl_version`: The version of the implementation of the specification. Nodes are free to ignore this; it serves only as an indication that the code is different; as long as the other two versions are the same then while the actual code may be different, it is nonetheless required to do the same thing. Non-consensus-breaking optimizations are about the only changes that could be made which would result in only the impl_version changing.
   * `transaction_version`: The version of the extrinsics interface. This number must be updated in the following circumstances: extrinsic parameters (number, order, or types) have been changed; extrinsics or pallets have been removed; or the pallet order in the construct_runtime! macro or extrinsic order in a pallet has been changed. If this number is updated, then the spec_version must also be updated 
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics
- [ ] If import a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- [ ] If needed, update our Javascript/Typescript APIs. These APIs are offcially used by exchanges or community developers.
- [ ] If modifying existing runtime storage items, make sure to implement storage migrations for the runtime and test them with `try-runtime`. This includes migrations inhreited from upstream changes, and you can search the diffs for modifications of `#[pallet::storage]` items to check for any.

2022-03-26 14:37 UTC, Dengjianping approved these changes
LGTM!

2022-03-27 19:15 UTC, stechu commented
If you look at `AssetRegistrarMetadata`'s implementation, like:

https://github.com/Manta-Network/Manta/blob/manta/runtime/primitives/src/assets.rs#L30 
```rust
/// The metadata of a Manta Asset
#[derive(Clone, Default, Eq, Debug, PartialEq, Ord, PartialOrd, Encode, Decode, TypeInfo)]
pub struct AssetRegistarMetadata<Balance> {
	pub name: Vec<u8>,
	pub symbol: Vec<u8>,
	pub decimals: u8,
	pub evm_address: Option<H160>,
	pub is_frozen: bool,
	pub min_balance: Balance,
	/// `is_sufficient`: Whether a non-zero balance of this asset is deposit of sufficient
	/// value to account for the state bloat associated with its balance storage. If set to
	/// `true`, then non-zero balances may be stored without a `consumer` reference (and thus
	/// an ED in the Balances pallet or whatever else is used to control user-account state
	/// growth).
	/// For example, if is_sufficient set to `false`, a fresh account cannot receive XCM tokens.
	pub is_sufficient: bool,
}
```
This is more than what `Pallet-Asset` can store. That's why `AssetIdMetadata` is needed.

2022-03-27 20:06 UTC, stechu requested changes

2022-03-27 20:06 UTC, stechu commented on pallets/asset-manager/src/lib.rs
> +			T::AssetRegistrar::update_asset_metadata(asset_id, metadata.clone().into())?;
Despite we use `transactional`, it is still a good practice to put the code that could fail before the code should never fail.

2022-04-09 22:07 UTC, stechu commented on pallets/asset-manager/src/lib.rs
> +				!asset_id.is_one(),
The logic only works for a specific configuration.
Should check `AssetConfig<Config>::NativeAssetId` instead of `one`.

2022-04-09 22:08 UTC, stechu requested changes
see the detailed comments.

2022-04-10 14:55 UTC, stechu approved these changes

2022-04-10 18:59 UTC, merged