fix: add CLI library back into node
Manta-Network/Manta pull request #607
Opened 2022-06-14 22:24 UTC by bhgomes

Signed-off-by: Brandon H. Gomes <bhgomes@pm.me>

## Description

Adds back the CLI node library removed by this commit: https://github.com/Manta-Network/Manta/commit/59d1bc483574e67cedeeb28c7fb9c4805ea50669.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests.
- [x] Updated relevant documentation in the code.
- [ ] Added **one** line describing your change in `<branch>/CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] If runtime changes, need to update the version numbers properly:
   * `authoring_version`: The version of the authorship interface. An authoring node will not attempt to author blocks unless this is equal to its native runtime.
   * `spec_version`: The version of the runtime specification. A full node will not attempt to use its native runtime in substitute for the on-chain Wasm runtime unless all of spec_name, spec_version, and authoring_version are the same between Wasm and native.
   * `impl_version`: The version of the implementation of the specification. Nodes are free to ignore this; it serves only as an indication that the code is different; as long as the other two versions are the same then while the actual code may be different, it is nonetheless required to do the same thing. Non-consensus-breaking optimizations are about the only changes that could be made which would result in only the impl_version changing.
   * `transaction_version`: The version of the extrinsics interface. This number must be updated in the following circumstances: extrinsic parameters (number, order, or types) have been changed; extrinsics or pallets have been removed; or the pallet order in the construct_runtime! macro or extrinsic order in a pallet has been changed. You can run the `metadata_diff.yml` workflow for help. If this number is updated, then the `spec_version` must also be updated 
- [ ] Verify benchmarks & weights have been updated for any modified runtime logics
- [ ] If importing a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- [ ] If needed, update our Javascript/Typescript APIs. These APIs are officially used by exchanges or community developers.
- [ ] If modifying existing runtime storage items, make sure to implement storage migrations for the runtime and test them with `try-runtime`. This includes migrations inherited from upstream changes, and you can search the diffs for modifications of `#[pallet::storage]` items to check for any.

2022-06-14 22:28 UTC, bhgomes commented
Seems the changelog was not updated to include a section to add unreleased updates, so I'm going to wait for that.

2022-06-15 20:02 UTC, ghzlatarev approved these changes, later dismissed

2022-06-20 06:16 UTC, Garandor reviewed
Pls add changelog and resolve conflicts

2022-06-20 06:20 UTC, Garandor reviewed
i don't see any functional changes in this PR, it seems to be type aliasing and refactoring only?

2022-06-20 16:04 UTC, bhgomes commented
> i don't see any functional changes in this PR, it seems to be type aliasing and refactoring only?

The change is to expose the `node` code as a library which is necessary for the CLI project. There are no functional changes.

2022-06-20 18:40 UTC, Garandor approved these changes
LGTM!

2022-06-20 18:46 UTC, Garandor requested changes
taking that back, CI is failing with missing module documentation

2022-06-20 19:44 UTC, bhgomes commented
> taking that back, CI is failing with missing module documentation

Yeah, fixing it now. The CI changed since last time and I wasn't ready for it yet.

2022-06-20 22:33 UTC, Garandor submitted a review, later dismissed
LGTM!

2022-06-22 03:29 UTC, Dengjianping commented on node/src/chain_specs/calamari.rs
> +pub type CalamariChainSpec = sc_service::GenericChainSpec<GenesisConfig, Extensions>;
I suppose it can be reused, can it be move to mod.rs?

2022-06-22 03:41 UTC, Dengjianping submitted a review, later dismissed
LGTM! But have to resolve the conflict. @bhgomes

2022-06-23 15:35 UTC, Garandor approved these changes

2022-06-28 06:41 UTC, ghzlatarev approved these changes

2022-06-28 06:41 UTC, merged