Release v3.3.0
Manta-Network/Manta pull request #764
Opened 2022-08-19 17:31 UTC by ghzlatarev

## Description

relates to: #751 

* Create changelog
* Update nimbus
* Disable parachain block parsing test

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Added **one** label out of the `L-` group to this PR
- [ ] Added **one or more** labels out of `A-` and `C-` groups to this PR
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

Situational Notes:
- If adding functionality, write unit tests!
- If importing a new pallet, choose a proper module index for it, and allow it in `BaseFilter`. Ensure **every** extrinsic works from front-end. If there's corresponding tool, ensure both work for each other.
- If needed, update our Javascript/Typescript APIs. These APIs are officially used by exchanges or community developers.
- If modifying existing runtime storage items, make sure to implement storage migrations for the runtime and test them with `try-runtime`. This includes migrations inherited from upstream changes, and you can search the diffs for modifications of `#[pallet::storage]` items to check for any.
- If runtime changes, need to update the version numbers properly:
   * `authoring_version`: The version of the authorship interface. An authoring node will not attempt to author blocks unless this is equal to its native runtime.
   * `spec_version`: The version of the runtime specification. A full node will not attempt to use its native runtime in substitute for the on-chain Wasm runtime unless all of spec_name, spec_version, and authoring_version are the same between Wasm and native.
   * `impl_version`: The version of the implementation of the specification. Nodes are free to ignore this; it serves only as an indication that the code is different; as long as the other two versions are the same then while the actual code may be different, it is nonetheless required to do the same thing. Non-consensus-breaking optimizations are about the only changes that could be made which would result in only the impl_version changing.
   * `transaction_version`: The version of the extrinsics interface. This number must be updated in the following circumstances: extrinsic parameters (number, order, or types) have been changed; extrinsics or pallets have been removed; or the pallet order in the construct_runtime! macro or extrinsic order in a pallet has been changed. You can run the `metadata_diff.yml` workflow for help. If this number is updated, then the `spec_version` must also be updated
- Verify benchmarks & weights have been updated for any modified runtime logics

2022-08-19 19:14 UTC, Garandor requested changes
Changelog seems incomplete, the rest LGTM

2022-08-19 19:20 UTC, Apokalip commented
> Changelog seems incomplete, the rest LGTM

The only missing parts are i think between manta and 3.3.0 (this branch) from what im seeing unless they dont have L labels or are Skipped, the others missing are L-skip

2022-08-19 19:34 UTC, Garandor commented
> unless they dont have L labels

Did you find any that dont have labels? pLs post them here so we can decide what to label them with ( or marking L-skip ) explicitly

2022-08-19 22:17 UTC, ghzlatarev commented
> > unless they dont have L labels
> 
> Did you find any that dont have labels? pLs post them here so we can decide what to label them with ( or marking L-skip ) explicitly

4/6 can be skipped:
https://github.com/Manta-Network/Manta/pull/709
https://github.com/Manta-Network/Manta/pull/700
https://github.com/Manta-Network/Manta/pull/714
https://github.com/Manta-Network/Manta/pull/757
The other 2 added to changelog (they were not labeled):
https://github.com/Manta-Network/Manta/pull/752
https://github.com/Manta-Network/Manta/pull/723

2022-08-20 04:11 UTC, Garandor approved these changes
LGTM codewise.

BUT: The `try_runtime` workflow failed with `ERR_UNHANDLED_REJECTION` for some reason.
https://github.com/Manta-Network/Manta/runs/7925056246?check_suite_focus=true#step:12:37

I'll re-run it again to see if it was a fluke

2022-08-20 05:55 UTC, ghzlatarev commented
> LGTM codewise.
> 
> BUT: The `try_runtime` workflow failed with `ERR_UNHANDLED_REJECTION` for some reason. https://github.com/Manta-Network/Manta/runs/7925056246?check_suite_focus=true#step:12:37
> 
> I'll re-run it again to see if it was a fluke

Something with the polkadot-js api code again, we should probably move that repo in here ... Anyway I ran it manually on my local machine and it worked:
```
2022-08-20 08:53:05 assembling new collators for new session 0 at #0    
2022-08-20 08:53:05 assembling new collators for new session 1 at #0    
2022-08-20 08:53:06 Connection established to target: Target { sockaddrs: [], host: "ws.calamari.systems", host_header: "ws.calamari.systems:443", _mode: Tls, path_and_query: "/" }
2022-08-20 08:53:06 scraping key-pairs from remote @ 0x1366d42e4c3302b17bec23eee5240dd7ff0589921742db7c2c7ab8a4311c14c0    
2022-08-20 08:53:06 downloading data for all pallets.    
2022-08-20 08:54:07 adding data for hashed key: 26aa394eea5630e07c48ae0c9558cef7f9cce9c888469bb1a0dceaa129672ef8    
2022-08-20 08:54:07 extending externalities with 1 manually injected key-values    
2022-08-20 08:54:07 👩‍👦 scraping child-tree data from 0 top keys    
2022-08-20 08:54:07 Custom("[backend]: frontend dropped; terminate client")
2022-08-20 08:54:07 injecting a total of 58514 top keys    
2022-08-20 08:54:08 injecting a total of 0 child keys    
2022-08-20 08:54:08 initialized state externalities with storage root 0x04d6b8bbe1a52574176c3b23365652a46ebf74a1e454b876cba32cb40b93073c    
2022-08-20 08:54:09 Connection established to target: Target { sockaddrs: [], host: "ws.calamari.systems", host_header: "ws.calamari.systems:443", _mode: Tls, path_and_query: "/" }
2022-08-20 08:54:10 found matching spec name: "calamari"    
2022-08-20 08:54:10 spec version mismatch (local 3300 != remote 3210). This could cause some issues.    
2022-08-20 08:54:10 Custom("[backend]: frontend dropped; terminate client")
2022-08-20 08:54:10 ✅ no migration for System    
2022-08-20 08:54:10 ✅ no migration for CalamariVesting    
2022-08-20 08:54:10 ✅ no migration for AssetManager    
2022-08-20 08:54:10 ✅ no migration for Assets    
2022-08-20 08:54:10 ✅ no migration for Multisig    
2022-08-20 08:54:10 ✅ no migration for Utility    
2022-08-20 08:54:10 ✅ no migration for XTokens    
2022-08-20 08:54:10 ✅ no migration for DmpQueue    
2022-08-20 08:54:10 ✅ no migration for CumulusXcm    
2022-08-20 08:54:10 ⚠️ PolkadotXcm declares internal migrations (which *might* execute). On-chain `StorageVersion(0)` vs current storage version `StorageVersion(0)`    
2022-08-20 08:54:10 ⚠️ XcmpQueue declares internal migrations (which *might* execute). On-chain `StorageVersion(1)` vs current storage version `StorageVersion(1)`    
2022-08-20 08:54:10 ✅ no migration for Scheduler    
2022-08-20 08:54:10 ✅ no migration for Preimage    
2022-08-20 08:54:10 ✅ no migration for Treasury    
2022-08-20 08:54:10 ✅ no migration for Aura    
2022-08-20 08:54:10 ✅ no migration for Session    
2022-08-20 08:54:10 ✅ no migration for CollatorSelection    
2022-08-20 08:54:10 ✅ no migration for Authorship    
2022-08-20 08:54:10 ✅ no migration for AuraAuthorFilter    
2022-08-20 08:54:10 ✅ no migration for AuthorInherent    
2022-08-20 08:54:10 ✅ no migration for TechnicalMembership    
2022-08-20 08:54:10 ✅ no migration for TechnicalCommittee    
2022-08-20 08:54:10 ✅ no migration for CouncilMembership    
2022-08-20 08:54:10 ✅ no migration for Council    
2022-08-20 08:54:10 ✅ no migration for Democracy    
2022-08-20 08:54:10 ✅ no migration for TransactionPayment    
2022-08-20 08:54:10 ✅ no migration for Balances    
2022-08-20 08:54:10 ✅ no migration for TransactionPause    
2022-08-20 08:54:10 ✅ no migration for ParachainInfo    
2022-08-20 08:54:10 ✅ no migration for Timestamp    
2022-08-20 08:54:10 ⚠️ ParachainSystem declares internal migrations (which *might* execute). On-chain `StorageVersion(1)` vs current storage version `StorageVersion(1)`    
2022-08-20 08:54:10 proof: 250f6465147c479c4f72977ea4015d0901b495e9424ba83b20fe320d453a0f33c90131cd52bc537646db8e0528b52ffd00586cbe035e8284410e542010b34a072469d59926e55799e6577d82e77c8d5e46cc8b5294acf3042ec794ebc10e63c27ef0713bd576b41b6e9a378032175f382e72b5c7634363f6b32c54adee15bb6e1a7abedd84ecbd09915bca94524a01920f500d350e3c2a94690899b24b77662b65973abbf8f5b3cd5c5376e9fce4d4a56121902adcd2d9bd11b1a74ac3422057b8a573bf3b756f3722c9ad7edd56d0b911f10bf19a91e964fe65f6845869b7856c7fbb1b24b8a697d3fc7cf2cb7d29b581947b3e6eee7fdcf45d26dddcddddddcdfc72b297c302bf3f1bd967efe36fefc9af1b99f27c3ff9337571999ac0e9efeb46a4bf5b0a35bc5eaf1ba67acaad4f4efe8c3565573fbb56b9c52fc4db39b7f84be03e6e327fc662974e16bb6cd8b5cfcfb18b5f3722ef681832a928c9d92f677b392cf4fbf7bb87b4733ddd88dafb76ee0bb1102b0f7b4f7e2a11a5de6523d3a93c1f37f933c9ae0f87a70ab7ff699347e0f6fbf5757361ff8972ebf3a92fc4d9763d37a74983a6ca56dbcea7f634a76093869a4d53ad7433e2afd7dc17e28c35d5a0fdaf5fb9a52fd9f5edecd7cfba93dcd2ffe1faf57553c1b9a5df9ee496be1067ac6dc753d3a0a36d9a34c4b9cfbf69d0d1bee61405cc7dfedd5ce05e...de02b9e3036a65f879a8d70d9ed59aeeae41ce2a54a2128807eb29db80208001b5818990641b4231adf5c34dde501c8bde3a4b09d1a10138fe2fc0a4d8b9dc808fafb627cb5b6464693a274af213ac47206899e3a932373afe3ce345632f4e899ee7e256f92e5888372d72f3e4db1003728980d48f4d64ac5d5ba0bdb0d6b133bab7e93eb3626704af857a228fef82bf671cc8505f0e7b9012096b41c4eb3aaf947f6ea429080100802730940261010a0d71afb1570ff8368d8fcfe186d826d0a247eb0ffebe98759c585f041315ccb80c166ca75d4dea3e9be88c100e00000080a5e436c4841865f149a39f2467b13037af02f28ed4feeb1a9d972d0e4d6f26c4809221a4d8a682288db5e2f58149b005df4841acdff7f3a57bc00ca45211173b328059b77850736675f99464c1fbdf1d266ce459a1b2528a15ebea4841356ebc7ebb9f05464cac3378d46f113cd5b7a4d71c8430428049d7b84fecf24adf829544d277efcd475adc60932aa2190201f610634032c478808a38fd1b4d07fb835fcae86dcdbf88fa41bff347d849eaeb3d0bb7074359aba880af7fcd30804be66a5fb5de588b8533c9915f61ad9000fd6e160c61e8d3f79869809f1883c6f1296191843cbcad0c623435c19eacd1344581b787483cb26232e03dc10340000080e31401dc2048463ac340bb733ed9c2d22a7378672d1dffb02fdff2358bf28f52 / 20 nodes    
2022-08-20 08:54:10 proof size: 796.21 KB (815321 bytes)    
2022-08-20 08:54:10 compact proof size: 795.65 KB (814742 bytes)    
2022-08-20 08:54:10 zstd-compressed compact proof 795.67 KB (814769 bytes)    
2022-08-20 08:54:10 TryRuntime_on_runtime_upgrade executed without errors. Consumed weight = 900000000, total weight = 500000000000 (0.0018)  
```

2022-08-20 06:16 UTC, Dengjianping approved these changes

2022-08-20 06:18 UTC, merged